FROM golang:1.24.4 AS builder
WORKDIR /usr/src/app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o /usr/local/bin/refresh cmd/refresh/refresh.go

FROM debian:bookworm-slim
COPY --from=builder /usr/local/bin/refresh /usr/local/bin/refresh
RUN apt-get update && \
    apt-get install -y ca-certificates && \
    rm -rf /var/lib/apt/lists/*
ENTRYPOINT ["/usr/local/bin/refresh"]
